// Cloudflare Worker entry ("main" in wrangler.jsonc). Wraps the Worker that
// OpenNext generates (.open-next/worker.js) and adds a scheduled() handler for
// the cron trigger, following the OpenNext "custom worker" pattern.
//
// The cron sends an in-process request to /api/cron/entitlements with the
// CRON_SECRET, so the scheduled run and a manual run take exactly the same
// code path (secret check, Asia/Singapore "today", idempotent inserts).
//
// Test the scheduled handler locally (CRON_SECRET in .dev.vars):
//   npm run cf:build && npx wrangler dev --test-scheduled
//   curl "http://localhost:8787/__scheduled?cron=5+16+*+*+*"

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore `.open-next/worker.js` is generated by `npm run cf:build`.
import { default as openNextWorker } from "./.open-next/worker.js";

type WorkerEnv = { CRON_SECRET?: string; BETTER_AUTH_URL?: string };
type WaitUntil = { waitUntil(promise: Promise<unknown>): void };
type ScheduledEvent = { cron: string; scheduledTime: number };

type FetchHandler = (request: Request, env: WorkerEnv, ctx: WaitUntil) => Promise<Response>;
const worker = openNextWorker as { fetch: FetchHandler };

const JOBS: Record<string, string> = {
  // 16:05 UTC = 00:05 Asia/Singapore, daily.
  "5 16 * * *": "/api/cron/entitlements",
};

const handler = {
  fetch: worker.fetch,

  async scheduled(event: ScheduledEvent, env: WorkerEnv, ctx: WaitUntil): Promise<void> {
    const path = JOBS[event.cron];
    if (!path) {
      console.error("scheduled: no job for cron", event.cron);
      return;
    }
    if (!env.CRON_SECRET) {
      throw new Error("scheduled: CRON_SECRET is not set on this Worker");
    }

    const origin = env.BETTER_AUTH_URL || "https://cron.internal";
    const request = new Request(new URL(path, origin), {
      method: "POST",
      headers: { authorization: `Bearer ${env.CRON_SECRET}` },
    });
    const response = await worker.fetch(request, env, ctx);
    const body = await response.text();
    if (!response.ok) {
      // Throwing marks the cron run as failed in the Cloudflare dashboard.
      throw new Error(`scheduled: ${path} returned ${response.status}: ${body.slice(0, 500)}`);
    }
    console.log(`scheduled: ${path}`, body);
  },
};

export default handler;
